[package]
name = "injective-protos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.10.0"
prost = "0.12.0"
prost-types = "0.12.0"
cosmos-sdk-proto = "0.19.0"
